name: Hi, I'm Salman
tagline: ""
location: Chicago, IL
portrait: /media/portrait.png
interests: When I'm not building products, I'm reading Marvel comics, perfecting
  my AeroPress recipe, or tinkering with side projects & AI.
handles:
  - label: Email
    href: mailto:shaheensalmant@gmail.com
  - label: LinkedIn
    href: https://linkedin.com/in/s0shaheen
